name: Netherite
main: Wertzui123\Netherite\Main
version: 2.3
api: 4.0.0
author: Wertzui123
load: POSTWORLD
description: A plugin to add netherite to your server
website: https://github.com/Wertzui123/Netherite